<a class="back-link" href="<?= e(url('dashboard')) ?>">← Dashboard</a>
<div class="page-heading"><div><span class="eyebrow">QUIZ BUILDER</span><h1><?= $quiz ? 'Racik ulang tantanganmu.' : 'Let’s make some chaos.' ?></h1><p class="muted">Soalnya dari kamu. Gangguannya dari kami.</p></div><?php if ($quiz): ?><span class="status-pill <?= $quiz['is_published'] ? 'published' : '' ?>">● <?= $quiz['is_published'] ? 'Published' : 'Draft' ?></span><?php endif; ?></div>
<div id="builder-error" class="notice error" role="alert" hidden></div>
<?php if ($quiz): ?>
<nav class="builder-shortcuts" aria-label="Pintasan builder"><a class="btn btn-secondary" href="#quiz-sharing">Bagikan tantangan ↑</a></nav>
<section id="quiz-sharing" class="panel form-panel mb-6 publish-panel" tabindex="-1"><div><span class="eyebrow">READY WHEN YOU ARE</span><h2>Bagikan tantangan.</h2><p class="muted mt-2">Publish membuka akses player. Unpublish menutup akses pengerjaan.</p><?php if ($quiz['is_published']): ?><div class="share-row mt-4"><input readonly aria-label="Link quiz" data-share-input="<?= e(url('quiz', ['q' => $quiz['public_id']])) ?>"><button type="button" class="btn btn-secondary" data-copy-link="<?= e(url('quiz', ['q' => $quiz['public_id']])) ?>">Salin link</button></div><?php endif; ?></div><div class="actions"><a class="btn btn-ghost" href="<?= e(url('results', ['id' => $quiz['id']])) ?>">Hasil & analytics ↗</a><form method="post" action="<?= e(url($quiz['is_published'] ? 'unpublish' : 'publish')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $quiz['id'] ?>"><button type="submit" class="btn <?= $quiz['is_published'] ? 'btn-secondary' : 'btn-primary' ?>"><?= $quiz['is_published'] ? 'Unpublish quiz' : 'Publish quiz ↗' ?></button></form></div></section>
<?php endif; ?>
<form id="builder-form" class="builder-layout">
    <div class="builder-main">
        <section class="panel form-panel"><div class="panel-heading"><span class="step-number">01</span><h2>Detail quiz</h2></div><div class="form-stack"><label>Judul quiz<input id="quiz-title" required maxlength="160" value="<?= e($quiz['title'] ?? '') ?>" placeholder="Kasih judul yang bikin penasaran"></label><label>Deskripsi <span class="muted font-normal">(opsional)</span><textarea id="quiz-description" rows="3" maxlength="5000" placeholder="Tentang apa quiz ini?"><?= e($quiz['description'] ?? '') ?></textarea></label></div></section>
        <section><div class="section-heading"><div class="panel-heading"><span class="step-number">02</span><h2>Pertanyaan <span id="question-count" class="muted text-base">0 / 30</span></h2></div></div><div id="questions" class="form-stack"></div><button id="add-question" class="btn add-question" type="button">＋ Tambah pertanyaan</button><p id="question-limit" class="muted text-sm mt-3" hidden>Batas 30 pertanyaan tercapai.</p></section>
    </div>
    <aside class="builder-sidebar">
        <section class="panel form-panel"><div class="panel-heading"><span class="step-number">03</span><h2>Atur pengalaman</h2></div><label class="switch-label"><span>Timer quiz<small class="muted block">Maksimal 30 menit</small></span><input id="timer-on" type="checkbox" <?= !empty($quiz['timer_minutes']) ? 'checked' : '' ?>></label><label id="timer-field" class="mt-4 block" <?= empty($quiz['timer_minutes']) ? 'hidden' : '' ?>>Durasi (menit)<input id="timer-minutes" type="number" min="1" max="30" step="1" value="<?= (int) ($quiz['timer_minutes'] ?? 10) ?>"></label><div class="divider"></div><fieldset><legend class="field-label">Rage Level</legend><p class="muted text-sm mb-4">Pilih tingkat kesabaran yang diuji.</p><?php foreach (['mild' => ['✳', 'Sedikit usil', '1 event / 4 soal'], 'annoying' => ['⌁', 'Mulai mengganggu', '1 event / 2 soal'], 'hell' => ['♨', 'Tidak ada soal yang tenang', '1 event / soal']] as $level => $info): ?><label class="rage-choice <?= e($level) ?>"><input type="radio" name="rage_level" value="<?= e($level) ?>" <?= ($quiz['rage_level'] ?? 'mild') === $level ? 'checked' : '' ?>><span class="rage-symbol"><?= e($info[0]) ?></span><span><strong><?= e(ucfirst($level)) ?></strong><small><?= e($info[1]) ?></small><small><?= e($info[2]) ?></small></span></label><?php endforeach; ?></fieldset><button id="save-quiz" class="btn btn-primary w-full mt-6" type="submit">Simpan quiz ↗</button><p id="save-status" class="muted text-xs mt-3" role="status">Simpan perubahan sebelum publish.</p></section>
    </aside>
</form>
<?php if ($quiz): ?>
<form class="delete-form" method="post" action="<?= e(url('delete')) ?>" data-confirm="Hapus quiz beserta seluruh attempt dan hasilnya? Tindakan ini tidak dapat dibatalkan."><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $quiz['id'] ?>"><button class="text-coral text-sm" type="submit">Hapus quiz</button></form>
<?php endif; ?>
<script type="application/json" id="builder-data"><?= json_script(['id' => $quiz ? (int) $quiz['id'] : null, 'revision' => (int) ($quiz['revision'] ?? 0), 'questions' => $questions]) ?></script>
<script type="module" src="assets/js/builder.js"></script>
